[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/demo"
  to = "/demo.html"
  status = 200

[[redirects]]
  from = "/demo2"
  to = "/demo2.html"
  status = 200

[[redirects]]
  from = "/classic"
  to = "/classic.html"
  status = 200
